stages:
  - lint

eslint:
  image: node:latest
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    - eslint --init
    # Run ESLint
    - eslint js --ignore-pattern 'lib/'

phpcs:
  image: texthtml/phpcs
  stage: lint
  script:
    - phpcs --standard=test/phpcs.ruleset.xml **.php
